angular.module('controllers',[]).controller('teacherCourseMissionListCtrl',
    ['$scope','$rootScope','$stateParams','$state','EducationUtil','$ionicLoading',
        function ($scope,$rootScope,$stateParams,$state,EducationUtil,$ionicLoading) {

        $rootScope.title = "作业详情";
        
        $scope.goTeacherCourseMissionDetail = function (missionDetail) {
            $rootScope.teacherCourseMissionDetail = missionDetail;
            $state.go("teacherCourseMissionDetail");
        }

        $scope.param = {
            studentCourseMissionList:[
                {
                    studentName:"李正凯",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'1',
                    homeWorkCommentMsg:'非常不错，完成的很好，再接再励'
                },
                {
                    studentName:"刘一宁",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'0',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'2',
                    homeWorkCommentMsg:'非常不错，完成的很好，再接再励'
                },
                {
                    studentName:"王一然",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"徐昊",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'1',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"李佳璇",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'0'
                },
                {
                    studentName:"王博",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'2',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"邓凯哲",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'0',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"李华民",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"张驰",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"毛欢",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'2',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"张欢",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"张琪",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'2',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"陈桂红",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"王燕",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"董靖宇",
                    className:'初二2班',
                    missionStatus:'1',
                    commitStatus:'1',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                },
                {
                    studentName:"李勇",
                    className:'初二2班',
                    missionStatus:'0',
                    commitStatus:'2',
                    missionBaseInfo:{
                        missionName:'背诵《雷电颂》最后两段。并完成模拟卷',
                    },
                    missionContentList:[
                        {playUrl:'http://extro.oss-cn-hangzhou.aliyuncs.com/classvidio.mp4'}
                    ],
                    missionComment:'0',
                    homeWorkCommentMsg:''
                }
            ],
            unCommitMissionNum : 0,
            commitMissionNum:0,
            tabChoose : 'commit'
        }

        angular.forEach($scope.param.studentCourseMissionList,function (val,index) {
            if(val.commitStatus=='2')
            {
                $scope.param.unCommitMissionNum++;
            }else
            {
                $scope.param.commitMissionNum++;
            }
        })
            
        $scope.chooseCommitStudent = function () {
            $scope.param.tabChoose = 'commit';
        }
        
        $scope.chooseUnCommitStudent = function () {
            $scope.param.tabChoose = 'unCommit';
        }
}])
